/**
 * Shared tools data used across the application
 * Contains all tool definitions with their metadata
 */

import {
  FileText,
  Inbox,
  Network,
  Image as ImageIcon,
  Sparkles,
  PanelsRightBottom,
  Scissors,
  Layers,
  Mail,
  Search,
  ShieldAlert,
  SplitSquareHorizontal,
  ArrowRightLeft,
} from "lucide-react"

export const tools = [
  {
    href: "/rewrite",
    title: "AI Email Rewriter",
    description: "Transform HTML emails to bypass spam filters and improve deliverability while maintaining your original message and design.",
    icon: Sparkles,
    color: "from-purple-500/10 to-pink-500/10",
    iconColor: "text-purple-500",
    borderColor: "border-purple-500/20",
  },
  {
    href: "/header-processor",
    title: "Email Header Processor",
    description: "Process and analyze email headers in batch mode. Remove tracking headers, sanitize sender information, and optimize headers for better deliverability.",
    icon: Inbox,
    color: "from-blue-500/10 to-cyan-500/10",
    iconColor: "text-blue-500",
    borderColor: "border-blue-500/20",
  },
  {
    href: "/eml-to-txt-converter",
    title: "EML to TXT Converter",
    description: "Convert multiple email files (.eml) to plain text format with timestamps. Extract text content from email files quickly and efficiently.",
    icon: FileText,
    color: "from-green-500/10 to-emerald-500/10",
    iconColor: "text-green-500",
    borderColor: "border-green-500/20",
  },
  {
    href: "/eml-text-extractor",
    title: "EML Text Extractor",
    description: "Extract plain text from multiple .eml files, remove headers and HTML, then combine all texts into a single file separated by _SPT_ tag.",
    icon: Scissors,
    color: "from-yellow-500/10 to-amber-500/10",
    iconColor: "text-yellow-500",
    borderColor: "border-yellow-500/20",
  },
  {
    href: "/email-source-separator",
    title: "Email Source Separator",
    description: "Separate email headers, plain text, and HTML parts. Select which parts to keep and download the modified email source as a text file.",
    icon: Layers,
    color: "from-violet-500/10 to-purple-500/10",
    iconColor: "text-violet-500",
    borderColor: "border-violet-500/20",
  },
  {
    href: "/html-to-img",
    title: "HTML to Image Converter",
    description: "Convert HTML code to high-quality PNG or JPEG images. Perfect for creating email previews, screenshots, or visual representations of HTML content.",
    icon: ImageIcon,
    color: "from-orange-500/10 to-red-500/10",
    iconColor: "text-orange-500",
    borderColor: "border-orange-500/20",
  },
  {
    href: "/ip-comparator",
    title: "IP Comparator",
    description: "Compare two IP address lists to find missing IPs. Identify unique addresses, common entries, and differences between IP lists with detailed statistics.",
    icon: Network,
    color: "from-indigo-500/10 to-violet-500/10",
    iconColor: "text-indigo-500",
    borderColor: "border-indigo-500/20",
  },
  {
    href: "/photo-editor",
    title: "Images Toolkit",
    description: "All-in-one image processing suite featuring image combination, Base64 encoding, and interactive image map editor for email campaigns.",
    icon: PanelsRightBottom,
    color: "from-teal-500/10 to-cyan-500/10",
    iconColor: "text-teal-500",
    borderColor: "border-teal-500/20",
  },
  {
    href: "/subject-rewrite",
    title: "AI Subject Line Rewriter",
    description: "Transform spam-triggering subject lines into deliverable, high-performing alternatives. Get 20 optimized versions for each input subject line with AI-powered spam filter bypass technology.",
    icon: Mail,
    color: "from-pink-500/10 to-purple-500/10",
    iconColor: "text-pink-500",
    borderColor: "border-pink-500/20",
  },
  {
    href: "/gmail-deliverability",
    title: "Gmail Deliverability Viewer",
    description: "Analyze email deliverability and view Gmail-specific headers and information.",
    icon: Search,
    color: "from-cyan-500/10 to-blue-500/10",
    iconColor: "text-cyan-500",
    borderColor: "border-cyan-500/20",
  },
  {
    href: "/ip-reputation",
    title: "IP Reputation Checker",
    description: "Check IP address reputation and blacklist status across multiple databases.",
    icon: ShieldAlert,
    color: "from-red-500/10 to-orange-500/10",
    iconColor: "text-red-500",
    borderColor: "border-red-500/20",
  },
  {
    href: "/text-file-mapper",
    title: "Text File Mapper",
    description: "Map and process text files with advanced filtering and transformation options.",
    icon: SplitSquareHorizontal,
    color: "from-slate-500/10 to-gray-500/10",
    iconColor: "text-slate-500",
    borderColor: "border-slate-500/20",
  },
  {
    href: "/ipv4-converter",
    title: "IPv4 Converter",
    description: "Convert IPv4 addresses to Integer, Hex, IPv6 (short and long) formats. Supports batch conversion of multiple IPs.",
    icon: ArrowRightLeft,
    color: "from-emerald-500/10 to-teal-500/10",
    iconColor: "text-emerald-500",
    borderColor: "border-emerald-500/20",
  },
] as const

